### ISSUE TITLE
Ambiguous /api/users/{id|username} endpoint

### ISSUE THREAD

**Issue by taylor-jones** [taylor-jones/employee-recognition-portal#34]
In the `UserAccountController.java` file, we have two endpoints that do distinguish themselves from each other:
```java
    @GetMapping("/{id}")
    public UserAccount getUserAccount(@PathVariable("id") final Long id) {
        return repository.findById(id);
    }

    @GetMapping("/{username}")
    public UserAccount getUserAccount(@PathVariable("username") final String username) {
        return repository.findByUsername(username);
    }
```

This causes a request made to `/api/users/1 (for example)` to cause an error thrown about an ambiguous endpoint. I noticed this while trying to work on the getting all the Awards for only a specific user. 

The `/{id}` was the original, but it seems like we've integrated the `/{username}` pretty heavily into the user authorization for the application, so I didn't want to try messing with it and breaking the app. In fact, I'm not sure the `/{id}` endpoint, itself, is even getting used anywhere. 

> For the record, I was able to find a workaround by just continuing to use the `/{username}` endpoint as well, so this is not something that needs attention right away. I just wanted to put it in writing, so we could reference the issue should it have a more important effect down the road.

**Comment by tmrietz** [comment]
Good catch. I'm not sure what the simplest way to handle this would be but may be happening in other controllers as well. I haven't checked yet.

Initial thoughts:
  - We could narrow down whether or not the /{id} endpoint is actually being used anywhere for a fetch and if not, delete it
  - We could standardize the endpoints across the controllers so that fetch-by-id endpoints are formatted like /i/{id} or something similar.

**Comment by taylor-jones** [comment]
I'm pretty sure one of @tmrietz PRs from this week took care of this issue, so I'm gonna close it.
